[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "distillery-bin"
dynamic = ["version"]
description = "Distillery CLI"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/ekristen/distillery"
Repository = "https://github.com/cataggar/pypi-distillery"

[project.scripts]
dist = "distillery_cli:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["python/distillery_cli"]
